#!/usr/bin/env python3
"""Generate the project index in the profile README from GitHub repositories."""

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from collections import defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
README_PATH = ROOT / "README.md"
CONFIG_PATH = ROOT / "data" / "projects.json"
START_MARKER = "<!-- AUTO-PROJECTS:START -->"
END_MARKER = "<!-- AUTO-PROJECTS:END -->"
API_ROOT = "https://api.github.com"


def api_get(path: str, token: str | None) -> Any:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "Sunnymark7-profile-sync",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(f"{API_ROOT}{path}", headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def fetch_repositories(owner: str) -> tuple[list[dict[str, Any]], bool]:
    profile_token = os.environ.get("PROFILE_REPO_TOKEN", "").strip()
    api_token = profile_token or os.environ.get("GITHUB_TOKEN", "").strip() or None

    if profile_token:
        try:
            repositories = api_get(
                "/user/repos?affiliation=owner&visibility=all&sort=updated&per_page=100",
                profile_token,
            )
            owned = [
                repo
                for repo in repositories
                if repo.get("owner", {}).get("login", "").casefold() == owner.casefold()
            ]
            return owned, True
        except urllib.error.HTTPError as error:
            print(
                f"warning: private repository lookup failed ({error.code}); using public API",
                file=sys.stderr,
            )

    encoded_owner = urllib.parse.quote(owner, safe="")
    repositories = api_get(
        f"/users/{encoded_owner}/repos?type=owner&sort=updated&per_page=100",
        api_token,
    )
    return repositories, False


def normalized_text(repo: dict[str, Any]) -> str:
    values = [repo.get("name", ""), repo.get("description") or ""]
    values.extend(repo.get("topics") or [])
    return " ".join(values).casefold()


def classify(repo: dict[str, Any], categories: list[dict[str, Any]]) -> str | None:
    topics = {str(topic).casefold() for topic in repo.get("topics") or []}
    for category in categories:
        if category["topic"].casefold() in topics:
            return category["topic"]

    haystack = normalized_text(repo)
    for category in categories:
        if any(keyword.casefold() in haystack for keyword in category.get("keywords", [])):
            return category["topic"]
    return None


def md_text(value: str) -> str:
    return " ".join(value.replace("|", "\\|").replace("<", "&lt;").split())


def repo_technologies(repo: dict[str, Any]) -> str:
    values: list[str] = []
    language = repo.get("language")
    if language:
        values.append(str(language))
    for topic in repo.get("topics") or []:
        if topic.startswith("project-") or topic in values:
            continue
        values.append(str(topic))
        if len(values) == 4:
            break
    return " ".join(f"`{md_text(value)}`" for value in values) or "—"


def repository_row(repo: dict[str, Any]) -> str:
    name = md_text(str(repo["name"]))
    url = str(repo["html_url"])
    description = md_text(repo.get("description") or "实验仓库，说明正在完善。")
    updated = str(repo.get("updated_at") or "")[:7] or "—"
    if repo.get("archived"):
        updated = f"Archived · {updated}"
    return f"| [**{name}**]({url}) | {description} | {repo_technologies(repo)} | `{updated}` |"


def count_badge(label: str, value: int, color: str) -> str:
    encoded_label = urllib.parse.quote(label.replace("-", "--").replace("_", "__"), safe="")
    return (
        f'<img src="https://img.shields.io/badge/{encoded_label}-{value}-{color}'
        '?style=flat-square" alt="'
        f'{label}: {value}">'
    )


def render_index(
    repositories: list[dict[str, Any]],
    categories: list[dict[str, Any]],
    private_access: bool,
) -> str:
    grouped: dict[str | None, list[dict[str, Any]]] = defaultdict(list)
    for repo in repositories:
        grouped[classify(repo, categories)].append(repo)

    public_total = sum(not repo.get("private", False) for repo in repositories)
    if private_access:
        private_total = sum(bool(repo.get("private")) for repo in repositories)
    else:
        private_total = sum(int(category.get("private_baseline", 0)) for category in categories)

    lines = [
        START_MARKER,
        "<!-- Generated by scripts/update_projects.py; do not edit this block manually. -->",
        "",
        '<p align="center">',
        f"  {count_badge('Public repositories', public_total, '38BDF8')}",
        f"  {count_badge('Private R&D', private_total, '2DD4BF')}",
        f"  {count_badge('Project groups', len(categories), 'A3E635')}",
        "</p>",
        "",
    ]

    for category in categories:
        category_repos = grouped.get(category["topic"], [])
        public_repos = sorted(
            (repo for repo in category_repos if not repo.get("private")),
            key=lambda repo: str(repo.get("updated_at") or ""),
            reverse=True,
        )
        if private_access:
            private_count = sum(bool(repo.get("private")) for repo in category_repos)
        else:
            private_count = int(category.get("private_baseline", 0))

        if not public_repos and not private_count:
            continue

        lines.extend(
            [
                f"### {category['icon']} {category['title']}　`{category['topic']}`",
                "",
                f"> {category['description']}",
                "",
            ]
        )
        if public_repos:
            lines.extend(
                [
                    "| Repository | Purpose | Technology | Updated |",
                    "| --- | --- | --- | --- |",
                    *(repository_row(repo) for repo in public_repos),
                    "",
                ]
            )
        if private_count:
            noun = "repository" if private_count == 1 else "repositories"
            lines.extend([f"🔒 **Private R&D** · {private_count} {noun}", ""])

    uncategorized = sorted(
        (repo for repo in grouped.get(None, []) if not repo.get("private")),
        key=lambda repo: str(repo.get("updated_at") or ""),
        reverse=True,
    )
    if uncategorized:
        lines.extend(
            [
                "### 🧭 待整理　`needs-project-topic`",
                "",
                "> 这些仓库已被自动发现；添加一个 `project-*` Topic 后会移动到对应项目组。",
                "",
                "| Repository | Purpose | Technology | Updated |",
                "| --- | --- | --- | --- |",
                *(repository_row(repo) for repo in uncategorized),
                "",
            ]
        )

    lines.extend(
        [
            "<sub>自动同步公开仓库；私有仓库只显示数量，不公开名称和链接。</sub>",
            "",
            END_MARKER,
        ]
    )
    return "\n".join(lines)


def replace_generated_section(readme: str, generated: str) -> str:
    if readme.count(START_MARKER) != 1 or readme.count(END_MARKER) != 1:
        raise ValueError("README must contain exactly one generated project section")
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        flags=re.DOTALL,
    )
    return pattern.sub(lambda _: generated, readme)


def main() -> None:
    config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    repositories, private_access = fetch_repositories(config["owner"])
    repositories = [
        repo
        for repo in repositories
        if repo.get("name", "").casefold() != config["profile_repository"].casefold()
        and (config.get("include_forks", False) or not repo.get("fork"))
    ]

    readme = README_PATH.read_text(encoding="utf-8")
    generated = render_index(repositories, config["categories"], private_access)
    updated = replace_generated_section(readme, generated)
    README_PATH.write_text(updated.rstrip() + "\n", encoding="utf-8", newline="\n")

    visibility = "public + private counts" if private_access else "public + configured private counts"
    print(f"profile index updated from {len(repositories)} repositories ({visibility})")


if __name__ == "__main__":
    main()
